# Site wide configuration

title: "MIT Sloan Coders Club"
description: "The MIT Sloan Coder’s Club provides an accessible, results-focused forum for MIT Sloan students  and the broader MIT community to:
(1) Learn the basics of programming, and start building apps, websites, and services
(2) Engage in activities to build knowledge, such as hack-a-thons and hosted talks
(3) Better understand issues of software architecture, to promote better informed business leaders interested in the technology space."
logo: # 120x120 px default image used for Twitter summary card
teaser: 'sloan-logo-master.png'
locale: en
url:
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:path

# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
